[versions]
# https://fabricmc.net/develop/
minecraft = "1.21.11"
yarnMappings = "1.21.11+build.1"
fabricLoader = "0.17.3"
fabricApi = "0.136.0+1.21.11"

fabricLanguageKotlin = "1.13.6+kotlin.2.2.20" # https://github.com/FabricMC/fabric-language-kotlin/releases

kotlin = "2.2.20" # Match this to the one above
loom = "1.11-SNAPSHOT" # https://github.com/FabricMC/fabric-loom/releases
ksp = "2.2.20-2.0.3" # https://github.com/google/ksp/releases

mcdev = "2.1.0" # https://central.sonatype.com/artifact/com.demonwav.mcdev/annotations
pods4k = "0.7.0" # https://github.com/daniel-rusu/pods4k/releases
kotlinpoet = "2.2.0" # https://github.com/square/kotlinpoet/releases/

modPublish = "1.0.0" # https://github.com/modmuss50/mod-publish-plugin

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
yarnMappings = { module = "net.fabricmc:yarn", version.ref = "yarnMappings" }
fabricLoader = { module = "net.fabricmc:fabric-loader", version.ref = "fabricLoader" }
fabricLoaderJunit = { module = "net.fabricmc:fabric-loader-junit", version.ref = "fabricLoader" }
fabricLanguageKotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabricLanguageKotlin" }
fabricApi = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabricApi" }

mcdev = { module = "com.demonwav.mcdev:annotations", version.ref = "mcdev" }
pods4k = { module = "com.danrusu.pods4k:pods4k", version.ref = "pods4k" } # The main library module, this contains the bottom 2. But since loom doesn't include transitive dependencies, we need to include them separately.
pods4k-core = { module = "com.danrusu.pods4k.immutable-arrays:core", version.ref = "pods4k" }
pods4k-transformations = { module = "com.danrusu.pods4k.immutable-arrays:transformations-to-standard-collections", version.ref = "pods4k" }

symbolProcessingApi = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
kotlinpoet = { module = "com.squareup:kotlinpoet", version.ref = "kotlinpoet" }
kotlinpoet-ksp = { module = "com.squareup:kotlinpoet-ksp", version.ref = "kotlinpoet" }

[bundles]
kotlinpoet = [
    "kotlinpoet",
    "kotlinpoet-ksp"
]


[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
loom = { id = "fabric-loom", version.ref = "loom" }
modPublish = { id = "me.modmuss50.mod-publish-plugin", version.ref = "modPublish" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
